# Generated by Django 4.0.2 on 2022-03-07 10:23

from django.db import migrations, models
import smapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='hash',
            field=models.CharField(blank=True, default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='lot',
            name='tracking_code',
            field=models.CharField(default=smapp.models.random_number, max_length=10),
        ),
        migrations.AlterField(
            model_name='lot',
            name='txId',
            field=models.CharField(blank=True, default=None, max_length=66),
        ),
    ]
