# Generated by Django 4.0.2 on 2022-03-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0002_alter_lot_hash_alter_lot_tracking_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
