# Generated by Django 4.0.3 on 2022-03-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0004_remove_ip_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='hash',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
