# Generated by Django 4.0.3 on 2022-03-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0005_alter_lot_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='txId',
            field=models.CharField(blank=True, default=None, max_length=66, null=True),
        ),
    ]
